### ISSUE TITLE
gsub DROP needs some work

### ISSUE THREAD

**Issue by frank-west-iii** [jamesmacwilliam/percona_ar#5]
When using an execute statement the `gsub` command is too inclusive. I was trying to drop an index and had this statement

```
execute "ALTER TABLE `links` DROP INDEX "\
  "`index_links_on_some_url_and_id`, "\
  "ADD INDEX `index_links_on_some_url` (`phishing_url`);"
```

This generated a query with `DROP COLUMN INDEX` instead of `DROP INDEX`.

In order to workaround this issue I replaced it with this (note `COLUMN` comment):

```
execute "ALTER TABLE `links` DROP INDEX "\
  "`index_links_on_some_url_and_id`, "\
  "ADD INDEX `index_links_on_some_url` (`phishing_url`); #COLUMN"
```

I could imagine that even with the addition of supporting adding and removing indexes that this is too inclusive. Imagine having a column with the word column in the name of the column. I don't know if I could drop it using this?

https://github.com/jamesmacwilliam/percona_ar/blob/5878f91fd093e985c025506685d367463cdd9b4c/lib/percona_ar/query_builder.rb#L23

**Comment by frank-west-iii** [comment]
Or what if I had a column named `dropped_count` to count the number of times I dropped my ball. This would convert it to an incorrect statement as well.

**Comment by ivanoblomov** [comment]
@jamesmacwilliam, doesn't https://github.com/jamesmacwilliam/percona_ar/commit/39d9f0f3c63a2cc5748854a0e4920f1baa2ae8ee close this too?

**Comment by jamesmacwilliam** [comment]
@ivanoblomov just about, there was one more case I needed to check off that I've linked above
